### ISSUE TITLE
[Suggestion]: Spanish Translation

### ISSUE THREAD

**Issue by TheLegendofSaram** [Fuzss/horseexpert#11]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

8.1.1

### Suggestion (Required)

I made a spanish translation, is the mexican spanish translation, here is the file
[es_mx.zip](https://github.com/Fuzss/horseexpert/files/14463864/es_mx.zip)

**Comment by Fuzss** [comment]
Merged in #12, thanks!
