### ISSUE TITLE
[Suggestion]:  Adding a tag to the monocle to make it activate the overlay, which could be added to other wearables - 1.19.2 Forge

### ISSUE THREAD

**Issue by celsiusqc** [Fuzss/horseexpert#2]
### Suggestion (Required)

Could you add a feature where if the wearable item has a tag such as "tag:items:forge:horsemonocle" which would then act as the monocole you already have?
This would make it so if you wear create goggles, i could add the tag to them as a datapack and have them act as your monocle does.
This gives more freedom to modpack makers and would be great to have.
Hopefully you see the potential :)
For forge 1.19.2 ;)

**Comment by Fuzss** [comment]
Added the `horseexpert:inspection_equipment` item tag in v8.1.0 for offering such functionality.
Will probably be backported to 1.19.2 at some point.

**Comment by linkovich2** [comment]
Any shot you'd still be willing to backport this feature to 1.19.2? :)
