### ISSUE TITLE
[Suggestion]: Make Curios Dependency Optional

### ISSUE THREAD

**Issue by linkovich2** [Fuzss/horseexpert#5]
### Suggestion (Required)

For those of us making vanilla+ modpacks, this mod would be cool to include, but having a curios slot for one item seems overkill. Any chance it could fall back to the head slot if curios isn't available? 

Mod version in question: 4.0.0-1.19.2

**Comment by Fuzss** [comment]
Changed in v8.1.0, both Curios and Trinkets are now optional with the fallback mechanism you described.
Will probably be backported to 1.19.2 at some point.

**Comment by linkovich2** [comment]
Any chance you'd still be willing to backport this change to 1.19.2?
